### ISSUE TITLE
Galanta Tower Max FP Level 4 & 5 Are Incorrect

### ISSUE THREAD

**Issue by eruber** [FOE-Tools/FOE-Tools.github.io#441]
Level 4 Max FP 200, but my Galanta indicates that its 210
Level 5 Max FP 270, but my Galanta indicates that its 290
I have not checked any other levels

**Comment by Heziode** [comment]
Since the update of InnoGames of this week that change values of Galata, it is a fucking nightmare to manage.

I have 210 in game:
![image](https://user-images.githubusercontent.com/16735076/110154129-2dd6cf00-7de4-11eb-8c20-6295d61c1899.png)


And 210 in FOE-Tools:

![image](https://user-images.githubusercontent.com/16735076/110154274-5f4f9a80-7de4-11eb-9b20-753f3bfb1f2d.png)

Don't you ?

**Comment by knider** [comment]
At level 33 -> 34, the top reward is 275 FP
At level 32 -> 33, the top reward is 265 FP
31 -> 32 = 255 FP
30 -> 31 = 250 FP
